// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenAIServer.Data;

#nullable disable

namespace OpenAIServer.Migrations
{
    [DbContext(typeof(OpenAIServerContext))]
    [Migration("20250527062505_LastEnemyFought")]
    partial class LastEnemyFought
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenAIServer.Entities.ERStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Deaths")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("EventList")
                        .HasColumnType("text[]");

                    b.Property<int?>("Events")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<int?>("GreatRune")
                        .HasColumnType("integer");

                    b.Property<int?>("HP")
                        .HasColumnType("integer");

                    b.Property<string>("LastEnemyFought")
                        .HasColumnType("text");

                    b.Property<int?>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<int?>("MaxHP")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryWeapon")
                        .HasColumnType("text");

                    b.Property<int?>("ResposneCount")
                        .HasColumnType("integer");

                    b.Property<int?>("Runes")
                        .HasColumnType("integer");

                    b.Property<string>("SecondaryWeapon")
                        .HasColumnType("text");

                    b.Property<string>("TertiaryWeapon")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ERStats");
                });
#pragma warning restore 612, 618
        }
    }
}
